### ISSUE TITLE
Localization Null check operator

### ISSUE THREAD

**Issue by riccardocescon** [Oberhauser-Dev/dart_packages#28]
I am getting this issue when calling showDurationPicker:
```
[log] Err : Null check operator used on a null value
      StackTrace : #0      DurationPickerMaterialLocalizations.of (package:material_duration_picker/src/localizations.dart:62:54)
      #1      _DurationPickerState.didChangeDependencies (package:material_duration_picker/material_duration_picker.dart:2401:57)
material_duration_picker.dart:2401
      #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5766:11)
framework.dart:5766
      #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593:5)
framework.dart:5593
      #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
framework.dart:4468
      #5      Element.updateChild (package:flutter/src/widgets/framework.dart:3963:18)
framework.dart:3963
```
This is how i call it:
```flutter
FilledButton(
              onPressed: () {
                showDurationPicker(
                  context: context,
                  initialDuration: Duration.zero,
                );
              },
              child: Text('Set Time'),
            ),
```

I have tried both with setting `DefaultDurationPickerMaterialLocalizations.delegate,` on the MaterialApp localizationsDelegates, with and without it
Am i missing somethign or is there an issue?
I am using `material_duration_picker: ^0.0.2+1`

**Comment by riccardocescon** [comment]
Also happens with v0.0.1

**Comment by Gustl22** [comment]
Hey there, thank you for raising the issue!

Are you able to execute the example?

Which flutter version are you using?

https://github.com/Oberhauser-Dev/dart_packages/blob/main/packages/material_duration_picker/example/lib/main.dart
If you can, it's likely you forgot something, although I don't see anything wrong with your implementation ATM.

**Comment by riccardocescon** [comment]
Hi,
I will let you know on monday, thank you!
