### ISSUE TITLE
material_duration_picker : Null check operator used on a null value

### ISSUE THREAD

**Issue by vcolella** [Oberhauser-Dev/dart_packages#29]
I'm trying to use it like this:

```
onTap: () {
        showDurationPicker(
              durationPickerMode: DurationPickerMode.ms,
              context: context,
        );
},
```

Here's the stack :

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown building _FormScope:
Null check operator used on a null value

The relevant error-causing widget was:
  Form-[LabeledGlobalKey<FormState>#fa340]
  Form:file:///C:/Users/Victor/AppData/Local/Pub/Cache/hosted/pub.dev/material_duration_picker-0.0.2+1/lib/material_duration_picker.dart:22  34:30

When the exception was thrown, this was the stack:
#0      DurationPickerMaterialLocalizations.of (package:material_duration_picker/src/localizations.dart:62:54)
#1      _DurationPickerState.didChangeDependencies (package:material_duration_picker/material_duration_picker.dart:2401:57)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5766:11)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593:5)
...     Normal element mounting (29 frames)
#32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#33     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#34     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047:32)
...     Normal element mounting (190 frames)
#224    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#225    Element.updateChild (package:flutter/src/widgets/framework.dart:3963:18)
#226    _LayoutBuilderElement._rebuildWithConstraints.updateChildCallback (package:flutter/src/widgets/layout_builder.dart:207:18)
#227    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3038:19)
#228    _LayoutBuilderElement._rebuildWithConstraints (package:flutter/src/widgets/layout_builder.dart:231:12)
#229    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2719:59)
#230    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1098:15)
#231    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2719:14)
#232    RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:278:5)
#233    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:369:5)
#234    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#235    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:234:12)
#236    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#237    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#238    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#239    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#240    RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:569:11)
#241    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#242    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#243    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1448:11)
#244    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#245    RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:291:14)
#246    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#247    RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:451:14)
#248    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#249    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:234:12)
#250    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#251    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:234:12)
#252    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#253    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:234:12)
#254    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#255    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#256    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#257    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#258    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#259    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#260    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#261    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#262    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#263    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#264    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#265    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#266    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#267    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#268    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3728:13)
#269    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#270    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#271    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#272    _RenderTheaterMixin.layoutChild (package:flutter/src/widgets/overlay.dart:1002:13)
#273    _RenderTheater.performLayout (package:flutter/src/widgets/overlay.dart:1311:9)
#274    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2446:7)
#275    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1052:18)
#276    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1065:15)
#277    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:602:23)
#278    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1164:13)
#279    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#280    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#281    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#282    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#283    _invoke (dart:ui/hooks.dart:312:13)
#284    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#285    _drawFrame (dart:ui/hooks.dart:283:31)
```

Any ideas ?

**Comment by Gustl22** [comment]
Thank you. Can you have a look here?
https://github.com/Oberhauser-Dev/dart_packages/issues/28#issuecomment-2523729724

**Comment by vcolella** [comment]
Will do
