### ISSUE TITLE
[flutter_release] Doesn't support l10n

### ISSUE THREAD

**Issue by orkun1675** [Oberhauser-Dev/dart_packages#31]
I'm seeing the following error:

```
Run ARTIFACT_PATH=$(dart pub global run flutter_release build \
  ARTIFACT_PATH=$(dart pub global run flutter_release build \
    ipa \
     \
     \
     \
     \
     \
     \
     \
     \
    | tail -1)
  ARTIFACT_NAME=$(basename "$ARTIFACT_PATH")
  echo "Artifact Path: $ARTIFACT_PATH"
  echo "artifact-path=$ARTIFACT_PATH" >> $GITHUB_OUTPUT
  echo "artifact-name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT
  shell: /opt/homebrew/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter/stable-3.24.5-arm64
    PUB_CACHE: /Users/runner/.pub-cache
    SSH_AUTH_SOCK: /var/folders/0w/4z5l9vds32nbkz7l22n8j6s80000gn/T//ssh-C5BXTR2YgSbe/agent.3560
    SSH_AGENT_PID: 3561
Unhandled exception:
Exception: Error (Xcode): Error: Couldn't resolve the package 'flutter_gen' in 'package:flutter_gen/gen_l10n/app_localizations.dart'.

Encountered error while archiving for device.

#0      runProcess (package:dart_release/utils/process.dart:28:29)
<asynchronous suspension>
#1      FlutterBuild.build (package:flutter_release/build.dart:72:20)
<asynchronous suspension>
#2      IosPlatformBuild._buildIosIpa (package:flutter_release/platform/ios.dart:228:22)
<asynchronous suspension>
#3      CommonBuildCommand.run (package:flutter_release/cli/build.dart:[82](https://github.com/ChunkyTofuStudios/destiwake-app/actions/runs/12271126256/job/34237469908#step:7:85):20)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#5      main (file:///Users/runner/.pub-cache/hosted/pub.dev/flutter_release-0.3.0/bin/flutter_release.dart:16:3)
<asynchronous suspension>
```

This error occurs even if I add an additional step before the `oberhauser-dev/flutter-release-action@v0` action:

```yaml
      - name: Get Flutter Dependencies
        run: |
          flutter pub get
          flutter gen-l10n
```

**Comment by Gustl22** [comment]
It does support l10n, but `flutter_gen` needs additional steps in order to work. Maybe you did it locally in the past already, but not on the ci:
https://pub.dev/packages/flutter_gen#installation

**Comment by orkun1675** [comment]
Thanks for the pointer, TIL!
